# Default values for cronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://crontab.guru/
schedule: "*/1 * * * *"

image:
  repository: docker.io/busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: stable
  command: ["echo"]
  args: ["cronjob"]

restartPolicy: OnFailure
concurrencyPolicy: Allow
startingDeadlineSeconds: 200
suspend: false
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 1
