{{- if or .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
data:
{{- range $key,$value := .Values.configmap }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
