apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  suspend: {{ .Values.suspend }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "deployment.fullname" . }}
          labels:
            {{- include "deployment.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: {{ .Values.image.command }}
              {{- if .Values.image.args }}
              args: {{ .Values.image.args }}
              {{- end }}

              {{- if or .Values.configmapFile .Values.secretFile .Values.volume }}
              volumeMounts:
            
              {{- range $key,$value := .Values.configmapFile }}
              {{- if or $value.mountPath }}
                - name: {{ $key | lower }}
                  mountPath: {{ $value.mountPath }}
                  {{- if or $value.subPath }}              
                  subPath: {{ $value.subPath }}
                  {{- end }}         
                  {{- if or $value.readOnly }}
                  readOnly: {{ $value.readOnly }}
                  {{- end }}
              {{- end }}
              {{- end }}

              {{- range $key,$value := .Values.secretFile }}
              {{- if or $value.mountPath }}
                - name: {{ $key | lower }}
                  mountPath: {{ $value.mountPath }}
                  {{- if or $value.subPath }}
                  subPath: {{ $value.subPath }}
                  {{- end }}
                  {{- if or $value.readOnly }}
                  readOnly: {{ $value.readOnly }}
                  {{- end }}
              {{- end }}
              {{- end }}

              {{- range $key,$value := .Values.volume }}
                - name: {{ $key | lower }}
                  mountPath: {{ $value }}
              {{- end }}

              {{- end }}

              {{- if or $.Values.env $.Values.configmap $.Values.secret }}
              env:

                {{- range $key,$value := .Values.env }}
                - name: {{ $key | upper }}
                  value: {{ $value | quote }}
                {{- end }}

                {{- range $key,$value := .Values.configmap }}
                - name: {{ $key | upper }}
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "deployment.fullname" $ }}
                      key: {{ $key }}
                {{- end }}

                {{- range $key,$value := .Values.secret }}
                - name: {{ $key | upper }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "deployment.fullname" $ }}
                      key: {{ $key }}
                {{- end }}

              {{- end }}

          {{- if or .Values.configmapFile .Values.secretFile .Values.volume }}
          volumes:

          {{- range $key,$value := .Values.configmapFile }}
            - name: {{ $key | lower }}
              configMap:
                name: {{ include "deployment.fullname" $ }}-{{ $key }}
          {{- end }}

          {{- range $key,$value := .Values.secretFile }}
            - name: {{ $key | lower }}
              secret:
                secretName: {{ include "deployment.fullname" $ }}-{{ $key }}
          {{- end }}

          {{- range $key,$value := .Values.volume }}
            - name: {{ $key | lower }}
              emptyDir: {}
          {{- end }}

          {{- end }}

          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          restartPolicy: {{ .Values.restartPolicy }}
