{{- if or .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment.fullname" $ }}
  labels:
    {{- include "deployment.labels" $ | nindent 4 }}
data:
{{- range $key,$value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
