{{- if or .Values.secretFile }}
{{- range $key,$value := .Values.secretFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployment.fullname" $ }}-{{ $key }}
  labels:
    {{- include "deployment.labels" $ | nindent 4 }}
data:
  {{ $key }}: |
      {{ $.Files.Get $value.file | b64enc }}
{{- end }}
{{- end }}
